In [1]:
from matplotlib import  pyplot as   plt
import numpy as np
import pandas as pd
from sklearn.model_selection import  train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import  accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import ConfusionMatrixDisplay


In [3]:
data=pd.read_csv("D:\\sgcode\\PYTHON\\ML\\neo.csv")


In [4]:
data.head()

id                 name  est_diameter_min  est_diameter_max  \
0  2162635  162635 (2000 SS164)          1.198271          2.679415   
1  2277475    277475 (2005 WK4)          0.265800          0.594347   
2  2512244   512244 (2015 YE18)          0.722030          1.614507   
3  3596030          (2012 BV13)          0.096506          0.215794   
4  3667127          (2014 GE35)          0.255009          0.570217   

   relative_velocity  miss_distance orbiting_body  sentry_object  \
0       13569.249224   5.483974e+07         Earth          False   
1       73588.726663   6.143813e+07         Earth          False   
2      114258.692129   4.979872e+07         Earth          False   
3       24764.303138   2.543497e+07         Earth          False   
4       42737.733765   4.627557e+07         Earth          False   

   absolute_magnitude  hazardous  
0               16.73      False  
1               20.00       True  
2               17.83      False  
3               22.20      False  
4               20.09       True

In [6]:
# Dropping the irrelavant feature
X = data.drop(['id','name','orbiting_body','sentry_object','hazardous'],axis=1)
print(X.shape)

(90836, 5)


In [ ]:
# Data cleaning

In [8]:
Y= LabelEncoder()
y=data['hazardous']
Y=Y.fit_transform(y)
print(Y)


[0 1 0 ... 0 0 0]


In [9]:
# Splitting the data in to train test
X_train,x_test,Y_train,y_test=train_test_split(X,Y,test_size=0.5)


In [10]:
# Fitting in to the Decision Tree model

model_DTC=DecisionTreeClassifier()
#print(model_DTC)
model_DTC.fit(X_train,Y_train)
prediction = model_DTC.predict(x_test)
print(prediction)
print(y_test)

[0 0 0 ... 0 0 0]
[0 0 0 ... 1 0 0]


In [11]:
#data visualisation

In [12]:
# To check the accuracy
accuracy= model_DTC.score(x_test,y_test)
print(accuracy)

0.8890527984499538


In [13]:
# Confusion matrix
#print(prediction)
#print(y_test)

confusion_model= pd.crosstab(prediction,y_test)
print(confusion_model)
print(classification_report(y_test,prediction))


col_0      0     1
row_0             
0      38443  2436
1       2603  1936
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     41046
           1       0.43      0.44      0.43      4372

    accuracy                           0.89     45418
   macro avg       0.68      0.69      0.69     45418
weighted avg       0.89      0.89      0.89     45418



In [14]:
#improvement in accuracy


In [15]:
#Univariate analysis

In [16]:
#Bivariate Analysis

In [17]:
#logistic Regression 

In [18]:
#Random Forest Classifier

In [19]:
#KNN algorithm